hedwig/config/routes.rb
Rails.application.routes.draw do
  resources :news_articles
  root to: 'news_articles#index'

end

hedwig/app/models/news_article.rb
class NewsArticle < ActiveRecord::Base
end

hedwig/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

hedwig/app/controllers/news_articles_controller.rb
class NewsArticlesController < ApplicationController
  before_action :set_news_article, only: [:show, :edit, :update, :destroy]

  # GET /news_articles
  # GET /news_articles.json
  def index
    @news_articles = NewsArticle.all
  end

  # GET /news_articles/1
  # GET /news_articles/1.json
  def show
  end

  # GET /news_articles/new
  def new
    @news_article = NewsArticle.new
  end

  # GET /news_articles/1/edit
  def edit
  end

  # POST /news_articles
  # POST /news_articles.json
  def create
    @news_article = NewsArticle.new(news_article_params)

    respond_to do |format|
      if @news_article.save
        format.html { redirect_to @news_article, notice: 'News article was successfully created.' }
        format.json { render :show, status: :created, location: @news_article }
      else
        format.html { render :new }
        format.json { render json: @news_article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news_articles/1
  # PATCH/PUT /news_articles/1.json
  def update
    respond_to do |format|
      if @news_article.update(news_article_params)
        format.html { redirect_to @news_article, notice: 'News article was successfully updated.' }
        format.json { render :show, status: :ok, location: @news_article }
      else
        format.html { render :edit }
        format.json { render json: @news_article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news_articles/1
  # DELETE /news_articles/1.json
  def destroy
    @news_article.destroy
    respond_to do |format|
      format.html { redirect_to news_articles_url, notice: 'News article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news_article
      @news_article = NewsArticle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_article_params
      params.require(:news_article).permit(:title, :content)
    end
end

hedwig/app/helpers/application_helper.rb
module ApplicationHelper
end

hedwig/app/helpers/news_articles_helper.rb
module NewsArticlesHelper
end

hedwig/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hedwig</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

hedwig/app/views/news_articles/_form.html.erb
<%= form_for(@news_article) do |f| %>
  <% if @news_article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news_article.errors.count, "error") %> prohibited this news_article from being saved:</h2>

      <ul>
      <% @news_article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_area :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

hedwig/app/views/news_articles/edit.html.erb
<h1>Editing News Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @news_article %> |
<%= link_to 'Back', news_articles_path %>

hedwig/app/views/news_articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing News Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @news_articles.each do |news_article| %>
      <tr>
        <td><%= news_article.title %></td>
        <td><%= news_article.content %></td>
        <td><%= link_to 'Show', news_article %></td>
        <td><%= link_to 'Edit', edit_news_article_path(news_article) %></td>
        <td><%= link_to 'Destroy', news_article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New News article', new_news_article_path %>

hedwig/app/views/news_articles/new.html.erb
<h1>New News Article</h1>

<%= render 'form' %>

<%= link_to 'Back', news_articles_path %>

hedwig/app/views/news_articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @news_article.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @news_article.content %>
</p>

<%= link_to 'Edit', edit_news_article_path(@news_article) %> |
<%= link_to 'Back', news_articles_path %>